version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-oauth
    container_name: api-oauth
    restart: always
    ports:
      - "8001:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: db
      DB_PORT: 1433
      DB_DATABASE: oauth_db
      DB_USERNAME: sa
      DB_PASSWORD: StrongPassw0rd!

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: api-oauth-sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: StrongPassw0rd!
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
